### ISSUE TITLE
delete pool 的时候 会导致 已打开的数据连接没有释放，程序重复启动多次后，数据库连接耗尽

### ISSUE THREAD

**Issue by czzCreator** [wuarmin/QtConnectionPool#4]
ConnectionPoolPrivate 缺一个析构函数 
delete pool 的时候 会导致 已打开的数据连接没有释放，程序重复启动多次后，数据库连接耗尽

最好 ConnectionPoolPrivate  能返回内部 的dbId 给外部

**Comment by wuarmin** [comment]
Hello @czzCreator, 

I don't speak Chinese, but a translater did his job. Thanks for the issue! 
I will check this, or you could post a PR.

BR

**Comment by wuarmin** [comment]
@czzCreator do you call `ConnectionPool().destroy();` at shutdown?

**Comment by czzCreator** [comment]
> ?

**Comment by czzCreator** [comment]
yes,thanks,i will try
