### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by hmoffatt** [wuarmin/QtConnectionPool#7]
The Qt documentation explicitly says that database connections should not be used on threads other than where they were created - https://doc.qt.io/qt-6/threads-modules.html#threads-and-the-sql-module

Did you find that it works despite this? Which database drivers did you test?

**Comment by wuarmin** [comment]
It has always worked for me. I have used and tested it with PostgreSql. In the meantime, however, I no longer use Qt productively.
